### ISSUE TITLE
um:ControlExtensions.Icon in Uno 5.2

### ISSUE THREAD

**Issue by igiona** [kazo0/DrawerApp#1]
Hi, first of all thanks for sharing the example application.

I'm getting issues while moving towards Uno 5.2:

```
			<um:ControlExtensions.Icon>
				<FontIcon FontWeight="Bold"
						  FontSize="24"
						  Glyph="&#xea8f;" />
			</um:ControlExtensions.Icon>
```
![image](https://github.com/kazo0/DrawerApp/assets/1524038/0c063f0b-1873-4b0f-919c-8ad1331c2784)

doesn't seem to be available in Uno 5.2 anymore.
Is there an alternative to it or is maybe behind a different namespace?

**Comment by kazo0** [comment]
Yeah the ControlExtensions along with a few other things were moved to the Uno.Themes namespace. Here is the link to the [upgrading docs for Uno Themes](https://platform.uno/docs/articles/external/uno.themes/doc/material-migration.html#upgrading-to-uno-themes-v5)

Specific section for ControlExtensions is [here](https://platform.uno/docs/articles/external/uno.themes/doc/material-migration.html#control-extensions)

**Comment by igiona** [comment]
> Yeah the ControlExtensions along with a few other things were moved to the Uno.Themes namespace. Here is the link to the [upgrading docs for Uno Themes](https://platform.uno/docs/articles/external/uno.themes/doc/material-migration.html#upgrading-to-uno-themes-v5)
> 
> Specific section for ControlExtensions is [here](https://platform.uno/docs/articles/external/uno.themes/doc/material-migration.html#control-extensions)

Perfect thanks!
